# Generated by Django 5.0.4 on 2024-07-25 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='flag',
            field=models.CharField(blank=True, choices=[('Scam', 'Scam'), ('Exchanged', 'Exchanged'), ('Gaveaway', 'Gaveaway')], max_length=30, null=True),
        ),
    ]
