# Generated by Django 5.0.4 on 2024-07-04 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Message', '0002_alter_conversation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-updated_at']},
        ),
    ]
