# Generated by Django 5.0.4 on 2024-07-04 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Message', '0003_alter_conversation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'ordering': ['-time_stamp']},
        ),
    ]
