# databases:
#   - name: mysitedb
#     plan: free
#     databaseName: WeShare
#     user: WeShare

services:
  - type: web
    plan: free
    name: WeShare
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn WeShare.asgi:application -k uvicorn.workers.UvicornWorker"
    # envVars:
    #   - key: DATABASE_URL
    #     fromDatabase:
    #       name: mysitedb
    #       property: connectionString
    #   - key: SECRET_KEY
    #     generateValue: true
    #   - key: WEB_CONCURRENCY
    #     value: 4