# Generated by Django 5.0.4 on 2024-05-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0007_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pic',
            field=models.ImageField(upload_to='images/profile_pics'),
        ),
    ]
