# Generated by Django 5.0.4 on 2024-05-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0003_rename_tag_tag_name_remove_post_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(blank=True, choices=[('Scam', 'Scam'), ('Sale & Buy', 'Sale & Buy')], max_length=30, null=True),
        ),
    ]
