# Generated by Django 5.0.4 on 2024-05-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0006_rename_comments_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='images/posts/'),
        ),
    ]
